name: CI/CD Pipeline for Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Lightsail
        run: |
          echo "Deploying to Lightsail..."
          scp -r ./ ubuntu@${{ secrets.LIGHTSAIL_IP }}:/
          ssh ubuntu@${{ secrets.LIGHTSAIL_IP }} 'chmod +x /start-your-app.sh && /start-your-app.sh'